services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app:create_app
    entrypoint:
      - /bin/sh
      - -c
      - "python3 scripts/init_db.py && gunicorn --bind 0.0.0.0:8000 'app:create_app()'"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app:create_app
    entrypoint:
      - /bin/sh
      - -c
      - "python3 scripts/init_db.py && gunicorn --bind 0.0.0.0:8000 'app:create_app()'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 5
